# Introduction
Singapore’s property market is often seen as an indicator of broader
social and economic trends (are the young people able to afford housing,
etc). Almost 80% of residents live in public housing known as Housing
and Development Board (HDB) flats. These are subsidized high rise
apartments that are sold on a 99-year leasehold which come with
restrictions such as a minimum occupation period.

There is also an extremely vibrant and active private housing sector
consisting of landed and non-landed properties which caters to a
wealthier class of citizens. The non-landed private properties such as
condominiums will be a closer comparison to HDBs rather than landed
residences which are standalone houses on a plot of land instead of
apartment buildings

Understanding the factors that drive property prices in Singapore is
both economically and socially relevant in the backdrop of rising
property prices globally.

Despite the government’s interventions to maintain affordability and
market stability, price dynamics continue to vary significantly across
regions, flat types, and lease duration. The government has continuously
implemented 'cooling measures' in multiple attempts to suppress the
growth of housing prices. While prices continue to climb, the pace has
moderated from the peak. Some also say that the pace have not slowed
down.

Some examples of 'cooling measures' - Increasing taxes on buyers with
more than one property, increasing tax on sellers who buy and resell
properties.

Even after these cooling measures, new records have been hit in 2025.

HDB: 415 resale flats sold for over SGD1M (USD770K) in the second
quarter of 2025 alone, and the total number of such transactions for
2025 is on track to exceed 1,500.

Private: Core Central Region (CCR): S\$2,612 psf (\~USD1.4M for an
average 2 bedroom at 700sqft) Rest of Central Region (RCR): S\$2,499 psf
(\~USD1.35M for an average 2 bedroom at 700sqft) Outside Central Region
(OCR): \~\$2,110 psf (\~USD1.15M for an average 2 bedroom at 700sqft)

We are excluding landed properties as they are only purchasable by
Singapore citizens, and prices are pre-tax.

Property market is too hot!


